<a href="https://colab.research.google.com/github/wonejomcoesr/Practica_calificada_01_zuasnabar/blob/main/Practica_calificada_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""PRACTICA_CALIFICADA_01: ZUASNABAR HUAMAN, ALEXIS"""

01

In [6]:
import pandas as pd
import numpy as np

# 1. Resolver con numpy los siguientes casos:

# 1.1 Crea un vector de números enteros del 1 al 20
print("Ejercicio: 01\n")
vector_1_20 = np.arange(1, 21)
print("Vector 1 a 20:", vector_1_20)

# 1.2 Crea una matriz de 3x3 con valores aleatorios entre 0 y 1
print("\nEjercicio: 02")
matriz_3x3 = np.random.rand(3,3)
print("\nMatriz 3x3 aleatoria entre 0 y 1:\n", matriz_3x3)

# 1.3 Redimensiona una matriz de 4x4 a una matriz de 2x8
print("\nEjercicio: 03")
matriz_4x4 = np.arange(16).reshape(4,4)
matriz_2x8 = matriz_4x4.reshape(2,8)
print("\nMatriz 4x4:\n", matriz_4x4)
print("\nMatriz redimensionada 2x8:\n", matriz_2x8)

# 1.4 Crea un array de 10 números equidistantes entre 0 y 1
print("\nEjercicio: 04")
array_equidistante = np.linspace(0, 1, 10)
print("\nArray de 10 números equidistantes entre 0 y 1:", array_equidistante)

# 1.5 Concatena dos vectores vertical y horizontalmente
print("\nEjercicio: 05")
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
concat_horizontal = np.concatenate((vec1, vec2))
concat_vertical = np.concatenate((vec1.reshape(-1,1), vec2.reshape(-1,1)), axis=1)
print("\nConcatenación horizontal:", concat_horizontal)
print("Concatenación vertical:\n", concat_vertical)

Ejercicio: 01

Vector 1 a 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Ejercicio: 02

Matriz 3x3 aleatoria entre 0 y 1:
 [[0.34480363 0.26539661 0.8506273 ]
 [0.81599831 0.60102573 0.55381904]
 [0.17956    0.18573808 0.31041592]]

Ejercicio: 03

Matriz 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Matriz redimensionada 2x8:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

Ejercicio: 04

Array de 10 números equidistantes entre 0 y 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Ejercicio: 05

Concatenación horizontal: [1 2 3 4 5 6]
Concatenación vertical:
 [[1 4]
 [2 5]
 [3 6]]


02


In [9]:
# 2. Resolver las siguientes operaciones:

# Vectores para operaciones
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

# 2.1 Suma, resta, multiplicación y división de dos vectores
print("Ejercicio: 01")
suma = v1 + v2
resta = v1 - v2
multiplicacion = v1 * v2
division = v1 / v2
print("\nSuma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

# 2.2 Media, mediana y desviación estándar de un vector
print("\nEjercicio: 02")
media = np.mean(v1)
mediana = np.median(v1)
desviacion = np.std(v1)
print("\nMedia:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion)

# 2.3 Normaliza un vector dividiendo cada elemento por el valor máximo
print("\nEjercicio: 03")
v1_normalizado = v1 / np.max(v1)
print("\nVector normalizado:", v1_normalizado)

# 2.4 Índice del valor máximo y mínimo
print("\nEjercicio: 04")
indice_max = np.argmax(v1)
indice_min = np.argmin(v1)
print("\nÍndice valor máximo:", indice_max)
print("Índice valor mínimo:", indice_min)

# 2.5 Multiplicación matricial entre dos matrices 3x3
print("\nEjercicio: 05")
m1 = np.random.rand(3,3)
m2 = np.random.rand(3,3)
producto_matricial = np.dot(m1, m2)
print("\nProducto matricial 3x3:\n", producto_matricial)

Ejercicio: 01

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]

Ejercicio: 02

Media: 2.0
Mediana: 2.0
Desviación estándar: 0.816496580927726

Ejercicio: 03

Vector normalizado: [0.33333333 0.66666667 1.        ]

Ejercicio: 04

Índice valor máximo: 2
Índice valor mínimo: 0

Ejercicio: 05

Producto matricial 3x3:
 [[1.25465987 1.58644014 0.53003577]
 [0.35666043 0.68053393 0.27480702]
 [1.14796962 1.5536975  0.59542664]]


03

In [10]:
# 3. Resolver con numpy los siguientes casos:

vector_enteros = np.array([1,2,3,4,5,6,7,8,9,10,0,-1,-2,51,60,55])

# 3.1 Selecciona los elementos pares
print("Ejercicio: 01")
pares = vector_enteros[vector_enteros % 2 == 0]
print("\nElementos pares:", pares)

# 3.2 Filtra valores mayores que 5
print("\nEjercicio: 02")
mayores_5 = vector_enteros[vector_enteros > 5]
print("Valores mayores que 5:", mayores_5)

# 3.3 Filtra valores iguales a cero
print("\nEjercicio: 03")
iguales_cero = vector_enteros[vector_enteros == 0]
print("Valores iguales a 0:", iguales_cero)

# 3.4 Filtra valores negativos
print("\nEjercicio: 04")
negativos = vector_enteros[vector_enteros < 0]
print("Valores negativos:", negativos)

# 3.5 Aplica la media a valores mayores de 50
print("\nEjercicio: 05")
media_mayores_50 = np.mean(vector_enteros[vector_enteros > 50])
print("Media de valores mayores de 50:", media_mayores_50)

Ejercicio: 01

Elementos pares: [ 2  4  6  8 10  0 -2 60]

Ejercicio: 02
Valores mayores que 5: [ 6  7  8  9 10 51 60 55]

Ejercicio: 03
Valores iguales a 0: [0]

Ejercicio: 04
Valores negativos: [-1 -2]

Ejercicio: 05
Media de valores mayores de 50: 55.333333333333336


04

In [11]:
# 4. Resolver con numpy los siguientes casos:

# 4.1 Crea un vector de 10 elementos y reemplaza valores mayores que 5 con 0
print("Ejercicio: 01")
vec_10 = np.array([1,3,7,9,5,6,2,8,4,10])
vec_10[vec_10 > 5] = 0
print("\nVector con valores mayores a 5 reemplazados con 0:", vec_10)

# 4.2 Combina dos vectores booleanos con AND (&) y OR (|)
print("\nEjercicio: 02")
bool1 = np.array([True, False, True, False])
bool2 = np.array([True, True, False, False])
and_result = bool1 & bool2
or_result = bool1 | bool2
print("\nAND:", and_result)
print("OR:", or_result)

# 4.3 Cuenta cantidad de valores en un vector que son múltiplos de 3
print("\nEjercicio: 03")
vec_mult_3 = np.array([3,6,7,9,10,12,13])
cantidad_mult_3 = np.sum(vec_mult_3 % 3 == 0)
print("\nCantidad múltiplos de 3:", cantidad_mult_3)

# 4.4 Índices de elementos no nulos (np.nonzero)
print("\nEjercicio: 04")
vec_nulos = np.array([0, 1, 2, 0, 3, 0])
indices_no_nulos = np.nonzero(vec_nulos)[0]
print("Índices elementos no nulos:", indices_no_nulos)

# 4.5 Comprueba si todos los elementos en un array son mayores que un valor dado
print("\nEjercicio: 05")
valor_usuario = 2
array_check = np.array([3,4,5,6])
todos_mayores = np.all(array_check > valor_usuario)
print(f"\n¿Todos los elementos son mayores que {valor_usuario}?:", todos_mayores)

Ejercicio: 01

Vector con valores mayores a 5 reemplazados con 0: [1 3 0 0 5 0 2 0 4 0]

Ejercicio: 02

AND: [ True False False False]
OR: [ True  True  True False]

Ejercicio: 03

Cantidad múltiplos de 3: 4

Ejercicio: 04
Índices elementos no nulos: [1 2 4]

Ejercicio: 05

¿Todos los elementos son mayores que 2?: True


05

In [12]:
# 5. Resolver con numpy los siguientes casos:

# 5.1 Calcula el cuadrado de cada elemento en un vector
print("Ejercicio: 01")
vector_cuadrado = np.array([1,2,3,4,5])
cuadrado = vector_cuadrado ** 2
print("\nCuadrado de cada elemento:", cuadrado)

# 5.2 Utiliza la función exponencial para elevar todos los elementos a la misma potencia
print("\nEjercicio: 02")
exponencial = np.exp(vector_cuadrado)
print("Función exponencial aplicada:", exponencial)

# 5.3 Encuentra los valores máximos y mínimos en cada fila de una matriz
print("\nEjercicio: 03")
matriz_3x4 = np.array([[1,5,2,4],[3,0,6,8],[7,3,9,1]])
max_filas = np.max(matriz_3x4, axis=1)
min_filas = np.min(matriz_3x4, axis=1)
print("\nMáximos por fila:", max_filas)
print("Mínimos por fila:", min_filas)

# 5.4 Aplica la función sin a todos los elementos y almacena en otro vector
print("\nEjercicio: 04")
sin_vector = np.sin(vector_cuadrado)
print("\nSeno de cada elemento:", sin_vector)

# 5.5 Realiza la transpuesta de una matriz 3x4
print("\nEjercicio: 05")
transpuesta = matriz_3x4.T
print("\nTranspuesta de matriz 3x4:\n", transpuesta)

Ejercicio: 01

Cuadrado de cada elemento: [ 1  4  9 16 25]

Ejercicio: 02
Función exponencial aplicada: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Ejercicio: 03

Máximos por fila: [5 8 9]
Mínimos por fila: [1 0 1]

Ejercicio: 04

Seno de cada elemento: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Ejercicio: 05

Transpuesta de matriz 3x4:
 [[1 3 7]
 [5 0 3]
 [2 6 9]
 [4 8 1]]


06

In [14]:
# 6. Crear DataFrame con columnas: 'Nombre', 'Edad', 'Ciudad' con al menos 10 registros
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'María', 'Juan', 'Sofía', 'Pedro', 'Lucía', 'Diego', 'Marta'],
    'Edad': [23, 35, 42, 28, 19, 31, 45, 22, 34, 27],
    'Ciudad': ['Lima', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa', 'Cusco', 'Lima', 'Arequipa']
}

df = pd.DataFrame(data)
print("DataFrame original:\n", df)

# 6.1 Filtrar personas que tienen más de 25 años
print("\nEjercicio: 01")
mayores_25 = df[df['Edad'] > 25]
print("\nPersonas mayores de 25 años:\n", mayores_25)

# 6.2 Añadir columna 'Ingresos' con cualquier valor (por ejemplo, aleatorio)
print("\nEjercicio: 02")
df['Ingresos'] = np.random.randint(1000, 5000, size=len(df))
print("\nDataFrame con columna Ingresos:\n", df)

# 6.3 Promedio de la edad en el DataFrame
print("\nEjercicio: 03")
promedio_edad = df['Edad'].mean()
print("\nPromedio de edad:", promedio_edad)

# 6.4 Contar cuántas veces aparece cada ciudad
print("\nEjercicio: 04")
conteo_ciudad = df['Ciudad'].value_counts()
print("\nConteo por ciudad:\n", conteo_ciudad)

# 6.5 Agrupar por 'Ciudad' y calcular promedio de 'Edad' para cada ciudad
print("\nEjercicio: 05")
promedio_edad_ciudad = df.groupby('Ciudad')['Edad'].mean()
print("\nPromedio de edad por ciudad:\n", promedio_edad_ciudad)

# 6.6 Ordenar DataFrame por 'Edad' ascendente y luego descendente
print("\nEjercicio: 06")
orden_asc = df.sort_values(by='Edad')
orden_desc = df.sort_values(by='Edad', ascending=False)
print("\nOrden ascendente por Edad:\n", orden_asc)
print("\nOrden descendente por Edad:\n", orden_desc)


DataFrame original:
    Nombre  Edad    Ciudad
0     Ana    23      Lima
1    Luis    35     Cusco
2  Carlos    42      Lima
3   María    28  Arequipa
4    Juan    19     Cusco
5   Sofía    31      Lima
6   Pedro    45  Arequipa
7   Lucía    22     Cusco
8   Diego    34      Lima
9   Marta    27  Arequipa

Ejercicio: 01

Personas mayores de 25 años:
    Nombre  Edad    Ciudad
1    Luis    35     Cusco
2  Carlos    42      Lima
3   María    28  Arequipa
5   Sofía    31      Lima
6   Pedro    45  Arequipa
8   Diego    34      Lima
9   Marta    27  Arequipa

Ejercicio: 02

DataFrame con columna Ingresos:
    Nombre  Edad    Ciudad  Ingresos
0     Ana    23      Lima      2171
1    Luis    35     Cusco      1451
2  Carlos    42      Lima      1748
3   María    28  Arequipa      2433
4    Juan    19     Cusco      3397
5   Sofía    31      Lima      4473
6   Pedro    45  Arequipa      1935
7   Lucía    22     Cusco      4706
8   Diego    34      Lima      1163
9   Marta    27  Arequipa     

07


In [22]:
# 7. Filtros sobre archivo adjunto (asumo que es un CSV o tabla con columnas que incluyan 'carrera', 'año', 'semestre')

#Importamos el archivo excel

df = pd.read_excel('/content/universidad.xlsx')

# 7.1 Cuántos son de Ing. en sistemas
print("Ejercicio: 01")
cantidad_sistemas = df[df['Carrera'] == 'Ing. en sistemas'].shape[0]
print("Cantidad de Ing. en sistemas:", cantidad_sistemas)

# 7.2 Cuántos son de Lic. en derecho
print("\nEjercicio: 02")
cantidad_derecho = df[df['Carrera'] == 'Lic. en derecho'].shape[0]
print("Cantidad de Ing. en derecho:", cantidad_derecho)

# 7.3 Cuántos se inscribieron en 2015
print("\nEjercicio: 03")
cantidad_2015 = df[df['Inscripción'].astype(str).str.startswith('2015')].shape[0]
print("Cantidad inscritos en 2015:", cantidad_2015)

# 7.4 Cuántos son del 1 y 2 semestre
print("\nEjercicio: 04")
cantidad_semestres = df[df['Semestre'].isin([1,2])].shape[0]
print("Cantidad inscritos en 1 y 2 semestre:", cantidad_semestres)

Ejercicio: 01
Cantidad de Ing. en sistemas: 13

Ejercicio: 02
Cantidad de Ing. en derecho: 17

Ejercicio: 03
Cantidad inscritos en 2015: 23

Ejercicio: 04
Cantidad inscritos en 1 y 2 semestre: 22
